;;; My Custom Colour Theme


(defun color-theme-peril-sensitive-sunglasses ()
  "Black. Everywhere."
  (interactive)
  ;; Note that some of the things that make up a color theme are
  ;; actually variable settings!
  (color-theme-install
   '(color-theme-d-custom
     ((foreground-color . "BLACK")
      (background-color . "black")
      (mouse-color . "black")
      (cursor-color . "black")
      (border-color . "black")
      (background-mode . dark))
     ((Man-overstrike-face . bold)
      (Man-underline-face . underline)
      (apropos-keybinding-face . underline)
      (apropos-label-face . italic)
      (apropos-match-face . secondary-selection)
      (apropos-property-face . bold-italic)
      (apropos-symbol-face . bold)
      (goto-address-mail-face . italic)
      (goto-address-mail-mouse-face . secondary-selection)
      (goto-address-url-face . bold)
      (goto-address-url-mouse-face . highlight)
      (help-highlight-face . underline)
      (list-matching-lines-face . bold)
      (view-highlight-face . highlight))
     (default ((t (nil))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:bold t :italic t))))
     (calendar-today-face ((t (:underline t))))
     (cperl-array-face ((t (:foreground "BLACK" :background "black" :bold t))))
     (cperl-hash-face ((t (:foreground "BLACK" :background "black" :bold t))))
     (cperl-nonoverridable-face ((t (:foreground "BLACK"))))
     (custom-button-face ((t (nil))))
     (custom-changed-face ((t (:foreground "black" :background "black"))))
     (custom-documentation-face ((t (nil))))
     (custom-face-tag-face ((t (:underline t))))
     (custom-group-tag-face ((t (:foreground "black" :underline t))))
     (custom-group-tag-face-1 ((t (:foreground "black" :underline t))))
     (custom-invalid-face ((t (:foreground "black" :background "black"))))
     (custom-modified-face ((t (:foreground "black" :background "black"))))
     (custom-rogue-face ((t (:foreground "black" :background "black"))))
     (custom-saved-face ((t (:underline t))))
     (custom-set-face ((t (:foreground "black" :background "black"))))
     (custom-state-face ((t (:foreground "black"))))
     (custom-variable-button-face ((t (:bold t :underline t))))
     (custom-variable-tag-face ((t (:foreground "black" :underline t))))
     (diary-face ((t (:foreground "black"))))
     (ediff-current-diff-face-A ((t (:foreground "black" :background "black"))))
     (ediff-current-diff-face-Ancestor ((t (:foreground "black" :background "black"))))
     (ediff-current-diff-face-B ((t (:foreground "black" :background "black"))))
     (ediff-current-diff-face-C ((t (:foreground "black" :background "black"))))
     (ediff-even-diff-face-A ((t (:foreground "black" :background "black"))))
     (ediff-even-diff-face-Ancestor ((t (:foreground "black" :background "black"))))
     (ediff-even-diff-face-B ((t (:foreground "black" :background "black"))))
     (ediff-even-diff-face-C ((t (:foreground "black" :background "black"))))
     (ediff-fine-diff-face-A ((t (:foreground "black" :background "black"))))
     (ediff-fine-diff-face-Ancestor ((t (:foreground "black" :background "black"))))
     (ediff-fine-diff-face-B ((t (:foreground "black" :backg50505round "black"))))
     (ediff-fine-diff-face-C ((t (:foreground "black" :background "black"))))
     (ediff-odd-diff-face-A ((t (:foreground "black" :background "black"))))
     (ediff-odd-diff-face-Ancestor ((t (:foreground "black" :background "black"))))
     (ediff-odd-diff-face-B ((t (:foreground "black" :background "black"))))
     (ediff-odd-diff-face-C ((t (:foreground "black" :background "black"))))
     (eshell-ls-archive-face ((t (:foreground "black" :bold t))))
     (eshell-ls-backup-face ((t (:foreground "black"))))
     (eshell-ls-clutter-face ((t (:foreground "black" :bold t))))
     (eshell-ls-directory-face ((t (:foreground "black" :bold t))))
     (eshell-ls-executable-face ((t (:foreground "black" :bold t))))
     (eshell-ls-missing-face ((t (:foreground "black" :bold t))))
     (eshell-ls-product-face ((t (:foreground "black"))))
     (eshell-ls-readonly-face ((t (:foreground "black"))))
     (eshell-ls-special-face ((t (:foreground "black" :bold t))))
     (eshell-ls-symlink-face ((t (:foreground "black" :bold t))))
     (eshell-ls-unreadable-face ((t (:foreground "black"))))
     (eshell-prompt-face ((t (:foreground "black" :bold t))))
     (eshell-test-failed-face ((t (:foreground "black" :bold t))))
     (eshell-test-ok-face ((t (:foreground "black" :bold t))))
     (excerpt ((t (:italic t))))
     (fixed ((t (:bold t))))
     (flyspell-duplicate-face ((t (:foreground "black" :bold t :underline t))))
     (flyspell-incorrect-face ((t (:foreground "black" :bold t :underline t))))
     (font-lock-builtin-face ((t (:foreground "BLACK"))))
     (font-lock-comment-face ((t (:foreground "BLACK"))))
     (font-lock-constant-face ((t (:foreground "BLACK" :underline t))))
     (font-lock-function-name-face ((t (:foreground "BLACK" :background "black" :bold t))))
     (font-lock-keyword-face ((t (:foreground "BLACK" :background "black"))))
     (font-lock-string-face ((t (:foreground "black"))))
     (font-lock-type-face ((t (:foreground "BLACK" :background "black"))))
     (font-lock-variable-name-face ((t (:foreground "BLACK"))))
     (font-lock-warning-face ((t (:foreground "black" :background "black" :bold t :underline t))))
     (fringe ((t (:background "black"))))
     (gnus-cite-attribution-face ((t (:italic t))))
     (gnus-cite-face-1 ((t (:foreground "black"))))
     (gnus-cite-face-10 ((t (:foreground "black"))))
     (gnus-cite-face-11 ((t (:foreground "black"))))
     (gnus-cite-face-2 ((t (:foreground "black"))))
     (gnus-cite-face-3 ((t (:foreground "black"))))
     (gnus-cite-face-4 ((t (:foreground "black"))))
     (gnus-cite-face-5 ((t (:foreground "black"))))
     (gnus-cite-face-6 ((t (:foreground "black"))))
     (gnus-cite-face-7 ((t (:foreground "black"))))
     (gnus-cite-face-8 ((t (:foreground "black"))))
     (gnus-cite-face-9 ((t (:foreground "black"))))
     (gnus-emphasis-bold ((t (:bold t))))
     (gnus-emphasis-bold-italic ((t (:bold t :italic t))))
     (gnus-emphasis-italic ((t (:italic t))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :underline t))))
     (gnus-emphasis-underline-bold-italic ((t (:bold t :italic t :underline t))))
     (gnus-emphasis-underline-italic ((t (:italic t :underline t))))
     (gnus-group-mail-1-empty-face ((t (:foreground "black"))))
     (gnus-group-mail-1-face ((t (:foreground "black" :bold t))))
     (gnus-group-mail-2-empty-face ((t (:foreground "black"))))
     (gnus-group-mail-2-face ((t (:foreground "black" :bold t))))
     (gnus-group-mail-3-empty-face ((t (:foreground "black"))))
     (gnus-group-mail-3-face ((t (:foreground "black" :bold t))))
     (gnus-group-mail-low-empty-face ((t (:foreground "black"))))
     (gnus-group-mail-low-face ((t (:foreground "black" :bold t))))
     (gnus-group-news-1-empty-face ((t (:foreground "black"))))
     (gnus-group-news-1-face ((t (:foreground "black" :bold t))))
     (gnus-group-news-2-empty-face ((t (:foreground "black"))))
     (gnus-group-news-2-face ((t (:foreground "black" :bold t))))
     (gnus-group-news-3-empty-face ((t (nil))))
     (gnus-group-news-3-face ((t (:bold t))))
     (gnus-group-news-low-empty-face ((t (:foreground "black"))))
     (gnus-group-news-low-face ((t (:foreground "black" :bold t))))
     (gnus-header-content-face ((t (:foreground "black" :italic t))))
     (gnus-header-from-face ((t (:foreground "black"))))
     (gnus-header-name-face ((t (:foreground "black"))))
     (gnus-header-newsgroups-face ((t (:foreground "black" :italic t))))
     (gnus-header-subject-face ((t (:foreground "black"))))
     (gnus-signature-face ((t (:italic t))))
     (gnus-splash-face ((t (:foreground "black"))))
     (gnus-summary-cancelled-face ((t (:foreground "black" :background "black"))))
     (gnus-summary-high-ancient-face ((t (:foreground "black" :bold t))))
     (gnus-summary-high-read-face ((t (:foreground "black" :bold t))))
     (gnus-summary-high-ticked-face ((t (:foreground "black" :bold t))))
     (gnus-summary-high-unread-face ((t (:bold t))))
     (gnus-summary-low-ancient-face ((t (:foreground "black" :italic t))))
     (gnus-summary-low-read-face ((t (:foreground "black" :italic t))))
     (gnus-summary-low-ticked-face ((t (:foreground "black" :italic t))))
     (gnus-summary-low-unread-face ((t (:italic t))))
     (gnus-summary-normal-ancient-face ((t (:foreground "black"))))
     (gnus-summary-normal-read-face ((t (:foreground "black"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "black"))))
     (gnus-summary-normal-unread-face ((t (nil))))
     (gnus-summary-selected-face ((t (:underline t))))
     (highlight ((t (:background "black" :underline t))))
     (highlight-changes-delete-face ((t (:foreground "black" :underline t))))
     (highlight-changes-face ((t (:foreground "black"))))
     (highline-face ((t (:background "black" :underline t))))
     (holiday-face ((t (:background "black"))))
     (info-menu-5 ((t (:underline t))))
     (info-node ((t (:bold t :italic t))))
     (info-xref ((t (:bold t))))
     (italic ((t (:italic t))))
     (makefile-space-face ((t (:background "black"))))
     (message-cited-text-face ((t (:foreground "black"))))
     (message-header-cc-face ((t (:foreground "black"))))
     (message-header-name-face ((t (:foreground "black"))))
     (message-header-newsgroups-face ((t (:foreground "black" :bold t :italic t))))
     (message-header-other-face ((t (:foreground "black"))))
     (message-header-subject-face ((t (:foreground "black" :bold t))))
     (message-header-to-face ((t (:foreground "black" :bold t))))
     (message-header-xheader-face ((t (:foreground "black"))))
     (message-separator-face ((t (:foreground "black"))))
     (modeline ((t (:foreground "black" :background "black"))))
     (modeline-buffer-id ((t (:foreground "black" :background "black"))))
     (modeline-mousable ((t (:foreground "black" :background "black"))))
     (modeline-mousable-minor-mode ((t (:foreground "black" :background "black"))))
     (region ((t (:background "black" :underline t))))
     (secondary-selection ((t (:background "black"))))
     (show-paren-match-face ((t (:foreground "black" :background "black"))))
     (show-paren-mismatch-face ((t (:foreground "black" :background "black"))))
     (speedbar-button-face ((t (:foreground "black"))))
     (speedbar-directory-face ((t (:foreground "black"))))
     (speedbar-file-face ((t (:foreground "black"))))
     (speedbar-highlight-face ((t (:background "black"))))
     (speedbar-selected-face ((t (:foreground "black" :underline t))))
     (speedbar-tag-face ((t (:foreground "black"))))
     (term-black ((t (:foreground "black"))))
     (term-blackbg ((t (:background "black"))))
     (term-blue ((t (:foreground "black"))))
     (term-bluebg ((t (:background "black"))))
     (term-bold ((t (:bold t))))
     (term-cyan ((t (:foreground "black"))))
     (term-cyanbg ((t (:background "black"))))
     (term-default-bg ((t (nil))))
     (term-default-bg-inv ((t (nil))))
     (term-default-fg ((t (nil))))
     (term-default-fg-inv ((t (nil))))
     (term-green ((t (:foreground "black"))))
     (term-greenbg ((t (:background "black"))))
     (term-invisible ((t (nil))))
     (term-invisible-inv ((t (nil))))
     (term-magenta ((t (:foreground "black"))))
     (term-magentabg ((t (:background "black"))))
     (term-red ((t (:foreground "black"))))
     (term-redbg ((t (:background "black"))))
     (term-underline ((t (:underline t))))
     (term-white ((t (:foreground "black"))))
     (term-whitebg ((t (:background "black"))))
     (term-yellow ((t (:foreground "black"))))
     (term-yellowbg ((t (:background "black"))))
     (underline ((t (:underline t))))
     (vcursor ((t (:foreground "black" :background "black" :underline t))))
     (vhdl-font-lock-attribute-face ((t (:foreground "black"))))
     (vhdl-font-lock-directive-face ((t (:foreground "black"))))
     (vhdl-font-lock-enumvalue-face ((t (:foreground "black"))))
     (vhdl-font-lock-function-face ((t (:foreground "black"))))
     (vhdl-font-lock-prompt-face ((t (:foreground "black" :bold t))))
     (vhdl-font-lock-reserved-words-face ((t (:foreground "black" :bold t))))
     (vhdl-font-lock-translate-off-face ((t (:background "black"))))
     (vhdl-speedbar-architecture-face ((t (:foreground "black"))))
     (vhdl-speedbar-architecture-selected-face ((t (:foreground "black" :underline t))))
     (vhdl-speedbar-configuration-face ((t (:foreground "black"))))
     (vhdl-speedbar-configuration-selected-face ((t (:foreground "black" :underline t))))
     (vhdl-speedbar-entity-face ((t (:foreground "black"))))
     (vhdl-speedbar-entity-selected-face ((t (:foreground "black" :underline t))))
     (vhdl-speedbar-instantiation-face ((t (:foreground "black"))))
     (vhdl-speedbar-instantiation-selected-face ((t (:foreground "black" :underline t))))
     (vhdl-speedbar-package-face ((t (:foreground "black"))))
     (vhdl-speedbar-package-selected-face ((t (:foreground "black" :underline t))))
     (viper-minibuffer-emacs-face ((t (:foreground "black" :background "black"))))
     (viper-minibuffer-insert-face ((t (:foreground "black" :background "black"))))
     (viper-minibuffer-vi-face ((t (:foreground "black" :background "black"))))
     (viper-replace-overlay-face ((t (:foreground "black" :background "black"))))
     (viper-search-face ((t (:foreground "black" :background "black"))))
     (widget-button-face ((t (:bold t))))
     (widget-button-pressed-face ((t (:foreground "black"))))
     (widget-documentation-face ((t (:foreground "black"))))
     (widget-field-face ((t (:background "black"))))
     (widget-inactive-face ((t (:foreground "black"))))
     (widget-single-line-field-face ((t (:background "black")))))))
